AparejosApp/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using AparejosApp.Models;
using static AparejosApp.Models.Enumeradores;

namespace AparejosApp.Controllers
{
    public class PedidosController : Controller
    {

        private AparejosEntities db = new AparejosEntities();

        // GET: Pedidos
        public ActionResult Index(string rangoFechas = "",
                                  TipoFiltroPedidos tipoFiltro = TipoFiltroPedidos.Normal)
        {
            List<Pedido> pedidos = new List<Pedido>();
            DateTime fechaDesde = new DateTime(1000000);
            DateTime fechaHasta = new DateTime();
            bool fechaDesdeCorrecta = false;
            bool fechaHastaCorrecta = false;
            
            switch (tipoFiltro)
            {
                case TipoFiltroPedidos.Normal:
                    pedidos = db.Pedido.Include(p => p.Clientes)
                        .Include(p => p.EstadoFabricacionPedido)
                        .Include(p => p.EstadoPagoPedido)
                        .Include(p => p.Productos)
                        .Include(p => p.TipoPedido)
                        .Include(p => p.TipoCarro)
                        .ToList();
                    break;
                case TipoFiltroPedidos.PorRangoFechaYTerminados:
                    if (!String.IsNullOrEmpty(rangoFechas))
                    {
                        fechaDesdeCorrecta = DateTime.TryParse(rangoFechas.Split('-')[0].Trim(), out fechaDesde);
                        fechaHastaCorrecta = DateTime.TryParse(rangoFechas.Split('-')[1].Trim(), out fechaHasta);
                    }
                    if (fechaDesdeCorrecta && fechaHastaCorrecta)
                    {
                        pedidos = db.Pedido.Include(p => p.Clientes)
                        .Include(p => p.EstadoFabricacionPedido)
                        .Include(p => p.EstadoPagoPedido)
                        .Include(p => p.Productos)
                        .Include(p => p.TipoPedido)
                        .Include(p => p.TipoCarro)
                        .Where(p => p.EstadoFabricacionPedidoID == (int)Enumeradores.EstadoFabricacionPedido.Terminado
                            && p.FechaModificacion >= fechaDesde && p.FechaModificacion <= fechaHasta)
                        .OrderByDescending(p => p.FechaModificacion).ToList();
                    }
                    break;
                case TipoFiltroPedidos.Terminados:
                    pedidos.AddRange(db.Pedido.Include(p => p.Clientes)
                        .Include(p => p.EstadoFabricacionPedido)
                        .Include(p => p.EstadoPagoPedido)
                        .Include(p => p.Productos)
                        .Include(p => p.TipoPedido)
                        .Include(p => p.TipoCarro)
                        .Where(p => p.EstadoFabricacionPedidoID == (int)Enumeradores.EstadoFabricacionPedido.Terminado
                            && p.TipoPedidoID == (int)Enumeradores.TipoPedido.Urgente)
                        .OrderByDescending(p => p.FechaModificacion).ToList());

                    pedidos.AddRange(db.Pedido.Include(p => p.Clientes)
                        .Include(p => p.EstadoFabricacionPedido)
                        .Include(p => p.EstadoPagoPedido)
                        .Include(p => p.Productos)
                        .Include(p => p.TipoPedido)
                        .Include(p => p.TipoCarro)
                        .Where(p => p.EstadoFabricacionPedidoID == (int)Enumeradores.EstadoFabricacionPedido.Terminado
                            && p.TipoPedidoID == (int)Enumeradores.TipoPedido.Reclamo)
                        .OrderByDescending(p => p.FechaModificacion).ToList());

                    pedidos.AddRange(db.Pedido.Include(p => p.Clientes)
                        .Include(p => p.EstadoFabricacionPedido)
                        .Include(p => p.EstadoPagoPedido)
                        .Include(p => p.Productos)
                        .Include(p => p.TipoPedido)
                        .Include(p => p.TipoCarro)
                        .Where(p => p.EstadoFabricacionPedidoID == (int)Enumeradores.EstadoFabricacionPedido.Terminado
                            && p.TipoPedidoID == (int)Enumeradores.TipoPedido.Normal)
                        .OrderByDescending(p => p.FechaModificacion).ToList());
                    break;
            }

            return View(pedidos);
        }
        
        // GET: Pedidos/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedido.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedidos/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.Clientes.Where(x => x.Activo != null && x.Activo.Value), "ID", "NombreApellido");
            //ViewBag.EstadoFabricacionPedidoID = new SelectList(db.EstadoFabricacionPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.EstadoPagoPedidoID = new SelectList(db.EstadoPagoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.ProductoID = new SelectList(db.Productos.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.ListProductos = GetListProductos();
            ViewBag.TipoPedidoID = new SelectList(db.TipoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.TipoCarroID = new SelectList(db.TipoCarro.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            return View();
        }

        private List<SelectProducto> GetListProductos()
        {
            List<SelectProducto> listProductos = new List<SelectProducto>();
            listProductos.AddRange(db.Productos.Where(x => x.Activo != null && x.Activo.Value).Select(y => new SelectProducto() {
                ID = y.ID,
                Precio = y.Precio
            }).ToList());

            return listProductos;
        }
        // POST: Pedidos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.Activo = true;
                pedido.FechaCreacion = DateTime.Now;
                pedido.EstadoFabricacionPedidoID = (int)Enumeradores.EstadoFabricacionPedido.Pedido;
                db.Pedido.Add(pedido);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.Clientes.Where(x => x.Activo != null && x.Activo.Value), "ID", "NombreApellido");
            ViewBag.EstadoFabricacionPedidoID = new SelectList(db.EstadoFabricacionPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.EstadoPagoPedidoID = new SelectList(db.EstadoPagoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.ProductoID = new SelectList(db.Productos.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.ListProductos = GetListProductos();
            ViewBag.TipoPedidoID = new SelectList(db.TipoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            ViewBag.TipoCarroID = new SelectList(db.TipoCarro.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion");
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedido.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.Clientes.Where(x => x.Activo != null && x.Activo.Value), "ID", "NombreApellido", pedido.ClienteID);
            ViewBag.EstadoFabricacionPedidoID = new SelectList(db.EstadoFabricacionPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion", pedido.EstadoFabricacionPedidoID);
            ViewBag.EstadoPagoPedidoID = new SelectList(db.EstadoPagoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion", pedido.EstadoPagoPedidoID);
            ViewBag.ProductoID = new SelectList(db.Productos.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion",pedido.ProductoID);
            ViewBag.ListProductos = GetListProductos();
            ViewBag.TipoPedidoID = new SelectList(db.TipoPedido.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion", pedido.TipoPedidoID);
            ViewBag.TipoCarroID = new SelectList(db.TipoCarro.Where(x => x.Activo != null && x.Activo.Value), "ID", "Descripcion", pedido.TipoCarroID);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

AparejosApp/Views/Pedidos/Create.cshtml
@model DataAccess.Pedido
@using AparejosApp.Models
@using AparejosApp.Mvc.Helpers
@{
    ViewBag.Title = "Agregar Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo</h2>

<style>
    label.error {
        color: red;
    }

    .valid {
        color: green;
    }
</style>

@*@using (Html.BeginForm("Create", "Pedidos", FormMethod.Post, new { @id = "form-pedido" })) 
{*@
<form id="form-pedido" action="@Url.Action("Create","Pedidos")" method="post">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID",null,"Seleccione...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductoID", null, "Seleccione...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TipoCarroID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoCarroID", null, "Seleccione...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoCarroID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.EstadoPagoPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoPagoPedidoID", null, "Seleccione...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoPagoPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoPedidoID", null, "Seleccione...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstimadaEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group date">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span><input type="text" name="FechaEstimadaEntrega" readonly="readonly" class="form-control" style="width:26.5%">
                </div>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrecio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrecio, new { htmlAttributes = new { @class = "form-control" } })
            </div>
           
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Observaciones, new { @class = "form-control", @rows = "4" })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="submitPedido" type="submit" value="Agregar" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>
@*}*@

<div>
    @Html.ActionLink("Volver", "Index")
</div>
@section Scripts{
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/locales/bootstrap-datepicker.es.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script type="text/javascript">
        var initialJsonData = {};
        @Html.RegisterJavascriptVariable("initialJsonData.ListProductos", (List<SelectProducto>)ViewBag.ListProductos)

    </script>
    <script src="~/Scripts/Pedidos/Pedidos-Create.js"></script>
    }

AparejosApp/Views/Pedidos/Delete.cshtml
@model DataAccess.Pedido

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaEstimadaEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEstimadaEntrega)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrecio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrecio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clientes.NombreApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clientes.NombreApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoFabricacionPedido.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoFabricacionPedido.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoPagoPedido.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoPagoPedido.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Productos.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productos.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPedido.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPedido.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCarro.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCarro.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AparejosApp/Views/Pedidos/Edit.cshtml
@model DataAccess.Pedido
@using AparejosApp.Models
@using AparejosApp.Mvc.Helpers
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    label.error {
        color: red;
    }

    .valid {
        color: green;
    }
</style>

<h2>Editar</h2>

@using (Html.BeginForm("Edit","Pedidos",FormMethod.Post, new { @id="form-pedido" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido Nº @Model.ID</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID",null, "Seleccione...", new { @class = "form-control" })
                @*@Html.DropDownList("ClienteID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductoID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TipoCarroID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoCarroID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoCarroID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoPedidoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoPagoPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoPagoPedidoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoPagoPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.EstadoFabricacionPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoFabricacionPedidoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoFabricacionPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstimadaEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="hidden" value="@Model.FechaEstimadaEntrega.ToString().Split(' ')[0]" id="FechaEstimadaHidden"/>
            <div class="col-md-10 input-group date">
                <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span><input type="text" name="FechaEstimadaEntrega" readonly="readonly" class="form-control" style="width:26.5%">
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrecio, htmlAttributes: new { @class = "control-label col-md-2"})
            
            <div class="col-md-10 input-group">
                <span class="input-group-addon">$</span>
                @Html.EditorFor(model => model.TotalPrecio, new { htmlAttributes = new { @class = "form-control", @readonly="readonly", @style = "width:26.5%" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Observaciones, new { @class = "form-control", @rows = "4" })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts{
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/locales/bootstrap-datepicker.es.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript">
        var initialJsonData = {};
        @Html.RegisterJavascriptVariable("initialJsonData.ListProductos", (List<SelectProducto>)ViewBag.ListProductos)

    </script>
    <script src="~/Scripts/Pedidos/Pedidos-Create.js"></script>
}

AparejosApp/Views/Pedidos/Index.cshtml
@model IEnumerable<DataAccess.Pedido>
@using AparejosApp.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/sweetalert.css" rel="stylesheet" />
<link href="~/Scripts/daterangepicker.css" rel="stylesheet" />
<h2>Index</h2>

<p>
    @Html.ActionLink("Agregar un pedido", "Create","Pedidos", new { @class = "btn btn-warning" })
</p>

<form class="row" method="get" action="@Url.Action("Index","Pedidos")">
    <div class="col-md-4">
        <input type="radio" name="tipoFiltro" value="@Enumeradores.TipoFiltroPedidos.PorRangoFechaYTerminados" />
        &nbsp;<label>Ver pedidos terminados entre fechas</label>
    </div>
    <div class="col-md-4">
        <input type="radio" name="tipoFiltro" value="@Enumeradores.TipoFiltroPedidos.Terminados" />
        &nbsp;<label>Ver pedidos terminados por prioridad</label>
    </div>
    <div class="col-md-2">
        <input type="radio" name="tipoFiltro" value="@Enumeradores.TipoFiltroPedidos.Normal" />
        &nbsp;<label>Ver Todos</label>
    </div>
    <div class="col-md-2">
        <input type="submit" value="Obtener" class="btn btn-success btn-block" />
    </div><br />
    <div class="form-group col-md-6" hidden id="RangoFechas">
        <label class="control-label">Seleccione las fechas:&nbsp;</label>
        <input class="form-control" type="text" name="rangoFechas" value="" />
    </div><br />
</form>
    

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Clientes.NombreApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoFabricacionPedido.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoPagoPedido.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoPedido.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCarro.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Clientes.NombreApellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoFabricacionPedido.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoPagoPedido.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Productos.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoPedido.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoCarro.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalle", "Details", new { id=item.ID }) |
            <a href="#" onclick="EliminarPedido(@item.ID)">Eliminar</a>
        </td>
    </tr>
}

</table>

@section Scripts{
    <script src="~/Scripts/sweetalert.min.js"></script>
    
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/daterangepicker.js"></script>
<script src="~/Scripts/Pedidos/Pedidos-General.js"></script>
    }